'use client';

import { motion } from 'framer-motion';
import { Cpu, Globe, Image as ImageIcon, Layout, Search, Zap } from 'lucide-react';

const features = [
    {
        title: 'AI Blog Generation',
        description: 'Powered by Gemini 2.0, generate 1000+ words of research-backed content in seconds.',
        icon: Cpu,
        color: 'emerald',
    },
    {
        title: 'Smart SEO Tools',
        description: 'Automatically optimized for Google, Answer Engines, and Generative AI parsers.',
        icon: Globe,
        color: 'blue',
    },
    {
        title: 'AI Image Engine',
        description: 'Every blog comes with a unique, high-definition featured image generated by AI.',
        icon: ImageIcon,
        color: 'purple',
    },
    {
        title: 'Deep Web Search',
        description: 'Our agent performs live web searches to ensure your content is factual and up-to-date.',
        icon: Search,
        color: 'orange',
    },
    {
        title: 'Clean Dashboard',
        description: 'Manage all your drafts, published blogs, and AI chats in one seamless interface.',
        icon: Layout,
        color: 'pink',
    },
    {
        title: 'Ultra Performance',
        description: 'Prophetic loading, Next.js server components, and Lighthouse 100 scores guaranteed.',
        icon: Zap,
        color: 'yellow',
    },
];

export default function Features() {
    return (
        <section id="features" className="py-24 bg-bg-dark relative overflow-hidden">
            <div className="max-w-7xl mx-auto px-6 relative z-10">
                <div className="text-center mb-16">
                    <h2 className="text-emerald-400 font-bold mb-4 tracking-widest uppercase text-sm">Features</h2>
                    <h3 className="text-4xl md:text-5xl font-black text-white">Everything you need to <br /> dominate the <span className="text-gradient">search results.</span></h3>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {features.map((feature, idx) => (
                        <motion.div
                            key={idx}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: idx * 0.1 }}
                            className="group p-8 rounded-3xl glass border-white/5 hover:border-emerald-500/30 transition-all duration-500 hover:translate-y-[-10px]"
                        >
                            <div className="w-14 h-14 bg-white/5 rounded-2xl flex items-center justify-center mb-6 border border-white/10 group-hover:bg-emerald-500/20 transition-colors">
                                <feature.icon className="w-6 h-6 text-white group-hover:text-emerald-400" />
                            </div>
                            <h4 className="text-xl font-bold text-white mb-3">{feature.title}</h4>
                            <p className="text-slate-400 leading-relaxed mb-6">
                                {feature.description}
                            </p>
                            <div className="h-1 w-12 bg-emerald-500/20 rounded-full group-hover:w-full transition-all duration-500" />
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
}
