'use client';

import { useState, useEffect } from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { blogApi, Blog } from '@/lib/api';
import { motion } from 'framer-motion';
import { Search, Calendar, User, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import { formatDate } from '@/lib/utils';

export default function BlogsPage() {
    const [blogs, setBlogs] = useState<Blog[]>([]);
    const [searchQuery, setSearchQuery] = useState('');
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchBlogs = async () => {
            try {
                const data = await blogApi.getAll();
                setBlogs(data);
            } catch (error) {
                console.error('Error fetching blogs:', error);
            } finally {
                setLoading(false);
            }
        };
        fetchBlogs();
    }, []);

    const filteredBlogs = blogs.filter(blog =>
        blog.topic.toLowerCase().includes(searchQuery.toLowerCase()) ||
        blog.content.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <main className="min-h-screen bg-bg-dark">
            <Navbar />

            <div className="pt-32 pb-20 max-w-7xl mx-auto px-6">
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-16">
                    <div>
                        <h1 className="text-4xl md:text-5xl font-black text-white mb-4">The AI <span className="text-gradient">Blog Feed</span></h1>
                        <p className="text-slate-400 max-w-xl">
                            Explore the latest insights generated by our AI agent. Research-backed, SEO-friendly, and always up-to-date.
                        </p>
                    </div>

                    <div className="relative group max-w-md w-full">
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500 group-focus-within:text-emerald-400 transition-colors" size={20} />
                        <input
                            type="text"
                            placeholder="Search blogs..."
                            className="w-full bg-white/5 border border-white/10 rounded-2xl py-4 pl-12 pr-6 text-white focus:outline-none focus:border-emerald-500/50 transition-all"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                        />
                    </div>
                </div>

                {loading ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {[1, 2, 3].map(i => (
                            <div key={i} className="h-96 rounded-3xl bg-white/5 animate-pulse" />
                        ))}
                    </div>
                ) : filteredBlogs.length > 0 ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        {filteredBlogs.map((blog, idx) => (
                            <motion.div
                                key={blog.id}
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: idx * 0.1 }}
                                className="group flex flex-col glass rounded-3xl overflow-hidden border-white/5 hover:border-emerald-500/30 transition-all"
                            >
                                {/* Image Placeholder or Featured Image if available */}
                                <div className="h-56 bg-gradient-to-br from-emerald-500/10 to-blue-500/10 relative overflow-hidden">
                                    <div className="absolute inset-0 flex items-center justify-center text-emerald-500/20 font-black text-6xl rotate-12">
                                        BLOG
                                    </div>
                                    {/* We will add real images logic in detail page */}
                                </div>

                                <div className="p-8 flex-1 flex flex-col">
                                    <div className="flex items-center gap-4 text-xs font-medium text-slate-500 mb-4">
                                        <span className="flex items-center gap-1"><Calendar size={14} /> {formatDate(blog.timestamp)}</span>
                                        <span className="flex items-center gap-1"><User size={14} /> AI Writer</span>
                                    </div>
                                    <h3 className="text-xl font-bold text-white mb-4 line-clamp-2 group-hover:text-emerald-400 transition-colors">
                                        {blog.topic}
                                    </h3>
                                    <p className="text-slate-400 text-sm line-clamp-3 mb-8 flex-1">
                                        {blog.content.replace(/[#*]/g, '').substring(0, 150)}...
                                    </p>

                                    <Link
                                        href={`/blogs/${blog.id}`}
                                        className="inline-flex items-center gap-2 text-emerald-400 font-bold hover:gap-3 transition-all"
                                    >
                                        Read Full Blog <ArrowRight size={18} />
                                    </Link>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                ) : (
                    <div className="text-center py-20">
                        <p className="text-slate-400 text-lg">No blogs found matching your search.</p>
                    </div>
                )}
            </div>

            <Footer />
        </main>
    );
}
